---
- name: Copy Repository File
  become: yes
  template:
        src: templates/mongo-org.repo.j2
        dest: /etc/yum.repos.d/mongodb-org-3.4.repo
  when: mongodb_install and (ansible_pkg_mgr == "yum")

# currently, there is a gpg key mismatch so I'm turning off checking for now
- name: Install MongoDB
  become: yes
  yum:
      name: "mongodb-org"
      state: present
      update_cache: yes
      disable_gpg_check: yes
  when: mongodb_install and (ansible_pkg_mgr == "yum")
